# Generated by Django 2.2.9 on 2020-01-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0026_client_multiple_response_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSAKeyFilesystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_key', models.FileField(help_text='Upload your private key here.', upload_to='oidc_provider/rsa_keys/', verbose_name='Key')),
            ],
            options={
                'verbose_name': 'RSA Key',
                'verbose_name_plural': 'RSA Keys',
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='RSAKey',
            new_name='RSAKeyDatabase',
        )
    ]
