# Generated by Django 2.2.9 on 2020-01-16 21:51

from django.db import migrations
from django.contrib.auth.hashers import make_password


def hash_client_secret(apps, schema_editor):
    Client = apps.get_model('oidc_provider', 'Client')

    for client in Client.objects.all():
        client.client_secret = make_password(client.client_secret)


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0026_client_multiple_response_types'),
    ]

    operations = [
        migrations.RunPython(hash_client_secret)
    ]
