# Generated by Django 2.2.9 on 2020-01-26 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0027_rsa_key_filesystem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='_redirect_uris',
            field=models.TextField(default='', help_text='Enter each URI on a new line. For native applications using looback addresses the port will be ignored to support applications binding to ephemeral ports.', verbose_name='Redirect URIs'),
        ),
    ]
