# Generated by Django 2.2.9 on 2020-01-27 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0029_rsa_key_storage'),
    ]

    operations = [
        # Add require_pkce with default=False so existing clients aren't changed
        migrations.AddField(
            model_name='client',
            name='require_pkce',
            field=models.BooleanField(default=False, help_text='Require PKCE (RFC7636) for public clients. You should only disable this if you know that the client does not support it. Has no effect on confidential clients.', verbose_name='Require PKCE?')
        ),
        # Change the default for new clients
        migrations.AlterField(
            model_name='Client',
            name='require_pkce',
            field=models.BooleanField(default=True, help_text='Require PKCE (RFC7636) for public clients. You should only disable this if you know that the client does not support it. Has no effect on confidential clients.', verbose_name='Require PKCE?')
        )
    ]
