# Generated by Django 2.2.9 on 2020-01-29 00:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0030_add_require_pkce'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='expires_at',
            new_name='access_expires_at'
        ),
        migrations.AlterField(
            model_name='token',
            name='access_expires_at',
            field=models.DateTimeField(verbose_name='Access Token Expiration Date')
        ),
        migrations.AddField(
            model_name='token',
            name='issued_at',
            field=models.DateTimeField(auto_now_add=True, null=True)
        ),
    ]
